In [1]:
# Loading the MNIST Dataset in Keras
import keras.api._v2.keras as keras
from tensorflow.keras.datasets import mnist
import numpy as np

In [2]:
# Load Dataset
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images.shape
(60000, 28, 28)
len(train_labels)
60000
train_labels
array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)
test_images.shape
(10000, 28, 28)
len(test_labels)
10000
test_labels
array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

11490434/11490434 [==============================] - 4s 0us/step


NameError: name 'array' is not defined

In [ ]:
# The Network Architecture
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
layers.Dense(512, activation="relu"),
layers.Dense(10, activation="softmax")
])

In [ ]:
# The Compilation Step
model.compile(optimizer="rmsprop",
loss="sparse_categorical_crossentropy",
metrics=["accuracy"])

In [ ]:
# Preparing The Image Data
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255
print(train_images.shape)
print(test_images.shape)
(60000, 784)
(10000, 784)

In [ ]:
# Train The Model
model.fit(train_images, train_labels, epochs=5, 
batch_size=128)

In [ ]:
# Using The Model to Make Predictions
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]
array([2.3584458e-07, 
3.7251192e-11, 
5.0270013e-05, 
1.3622823e-03,
7.4093059e-10, 
2.4309165e-06, 
4.2852251e-14, 
9.9853909e-01,
5.3168451e-06, 
4.0446674e-05], dtype=float32)
predictions[0].argmax()
7
predictions[0][7]
0.9985391
test_labels[0]
7

In [ ]:
# Evaluating the Model on New Data
test_loss, test_acc = model.evaluate(test_images, 
test_labels)
print(f"test_acc: {test_acc}")