In [8]:
# Constant Tensors & Variables

import tensorflow as tf

x= tf.ones(shape=(2, 1))
print(x)

x= tf.zeros(shape=(2, 1))
print(x)

x= tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

x= tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[-0.1414511 ]
 [ 0.30171663]
 [ 1.5225    ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.7046331 ]
 [0.60110664]
 [0.19187438]], shape=(3, 1), dtype=float32)


In [10]:
# Constant Tensors & Variables: Assignment yang error dikarenakan harus assign terlebih dahulu

import numpy as np
x= np.ones(shape=(2, 2))
x[0, 0] = 0.

import tensorflow as tf
x= tf.ones(shape=(2, 2))
x[0, 0] = 0.


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [13]:
# Constant Tensors & Variables: Assignment

v= tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

v.assign(tf.ones((3, 1)))
print(v)

v[0, 0].assign(3.)
print(v)

v.assign_add(tf.ones((3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.46506685],
       [ 0.69718117],
       [-1.2275548 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>


In [3]:
# Doing Math in TensorFlow

import tensorflow as tf

a= tf.ones((2, 2))
b= tf.square(a)             # Take the square
c= tf.sqrt(a)               # Take the square root
d= b + c                     # Add two tensors (element-wise)
e= tf.matmul(a, b)          # Take the product of two tensors
e*= d                       # Multiply two tensors (element-wise)

print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


In [5]:
# GradientTape API

input_var= tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    result= tf.square(input_var)
gradient= tape.gradient(result, input_var)

input_const= tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(input_const)
    result= tf.square(input_const)
gradient= tape.gradient(result, input_const)

time= tf.Variable(0.)

with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position= 4.9* time** 2
    speed= inner_tape.gradient(position, time)
acceleration= outer_tape.gradient(speed, time)

In [7]:
# The Base Layer Class in Keras

from tensorflow import keras 
class SimpleDense(keras.layers.Layer):
    def __init__(self, units, activation=None):
        super().__init__()
        self.units= units
        self.activation= activation
        
    def build(self, input_shape):
        input_dim=     input_shape[-1]
        self.W= self.add_weight(shape=(input_dim, self.units),initializer="random_normal")
        self.b= self.add_weight(shape=(self.units,),initializer="zeros")
        
    def call(self, inputs):
        y = tf.matmul(inputs, self.W) + self.b
        if self.activation is not None:
            y = self.activation(y)
        return y
    
my_dense= SimpleDense(units=32, activation=tf.  nn.relu)
input_tensor= tf.  ones(shape=(2  , 784))
output_tensor= my_dense(input_tensor)
print(output_tensor.shape)
(2, 32)

(2, 32)


(2, 32)

In [16]:
# Building Layers on The Fly

from tensorflow import keras
from tensorflow.keras import layers, models

model= models.Sequential([
    layers.Dense(
        32, activation="relu")
    ,layers.Dense(32)])

model= NaiveSequential([
    NaiveDense(input_size=784 , output_size=32, activation="relu"),
    NaiveDense(input_size=32, output_size=64, activation="relu"),
    NaiveDense(input_size=64, output_size=32, activation="relu"),
    NaiveDense(input_size=32, output_size=10, activation="softmax")
    ])

model= keras.Sequential([SimpleDense(32, activation="relu"),
                         SimpleDense(64, activation="relu"),
                         SimpleDense(32, activation="relu"),
                         SimpleDense(10, activation="softmax")])

NameError: name 'NaiveDense' is not defined

In [ ]:
# Configuring The Learning Process

model= keras.Sequential([keras.layers.Dense(1)])
model.compile(
    optimizer="rmsprop"
    ,loss="mean_squared_error"
    ,metrics=["accuracy"])

model.compile(
    optimizer=keras.optimizers.RMSprop()
    ,loss=keras.losses.MeanSquaredError()
    ,metrics=[keras.metrics.BinaryAccuracy()])

model.compile(
    optimizer=keras.optimizers.RMSprop(learning_rate=1e-4),
    loss=my_custom_loss,
    metrics=[my_custom_metric_1, my_custom_metric_2])

In [ ]:
# Training the Models

history= model.fit(
    inputs,
    targets,
    epochs=5,
    batch_size=128)

history.history

In [ ]:
# Using The validation_data Argument

import numpy as np

model= keras.Sequential([keras.layers.Dense(1)])
model.compile(
    optimizer=keras.optimizers.RMSprop(learning_rate=0.1),
    loss=keras.losses.MeanSquaredError(),
    metrics=[keras.metrics.BinaryAccuracy()])

indices_permutation= np.random.permutation(len(inputs))
shuffled_inputs= inputs[indices_permutation]
shuffled_targets= targets[indices_permutation]

num_validation_samples= int(0.3* len(inputs))
val_inputs= shuffled_inputs[:num_validation_samples]
val_targets= shuffled_targets[:num_validation_samples]
training_inputs= shuffled_inputs[num_validation_samples:]

training_targets= shuffled_targets[num_validation_samples:]
model.fit(
    training_inputs,training_targets,
    epochs=5,batch_size=16,
    validation_data=(val_inputs, val_targets)
)

In [ ]:
# Using The Models

predictions= model.predict(val_inputs, batch_size=128)
print(predictions[:10])